// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppReleaseDetail(arg1, arg2) {
  return window['go']['main']['App']['GetAppReleaseDetail'](arg1, arg2);
}

export function GetAppsConfig() {
  return window['go']['main']['App']['GetAppsConfig']();
}

export function GetCDNSettings() {
  return window['go']['main']['App']['GetCDNSettings']();
}

export function GetDownloadTask(arg1) {
  return window['go']['main']['App']['GetDownloadTask'](arg1);
}

export function GetReadmeByLink(arg1) {
  return window['go']['main']['App']['GetReadmeByLink'](arg1);
}

export function GetRepoStars(arg1) {
  return window['go']['main']['App']['GetRepoStars'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenSystemTerminal() {
  return window['go']['main']['App']['OpenSystemTerminal']();
}

export function SelectDownloadDirectory(arg1) {
  return window['go']['main']['App']['SelectDownloadDirectory'](arg1);
}

export function SetCDNSettings(arg1) {
  return window['go']['main']['App']['SetCDNSettings'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
