// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppReleaseDetail(arg1:string,arg2:string):Promise<main.AppReleaseDetail>;

export function GetAppsConfig():Promise<main.AppsConfig>;

export function GetCDNSettings():Promise<main.CDNSettings>;

export function GetDownloadTask(arg1:string):Promise<main.DownloadTaskSnapshot>;

export function GetReadmeByLink(arg1:main.ReadmeByLinkRequest):Promise<main.ReadmeByLinkResponse>;

export function GetRepoStars(arg1:Array<string>):Promise<Record<string, number>>;

export function Greet(arg1:string):Promise<string>;

export function OpenSystemTerminal():Promise<void>;

export function SelectDownloadDirectory(arg1:string):Promise<string>;

export function SetCDNSettings(arg1:main.SetCDNSettingsRequest):Promise<main.CDNSettings>;

export function StartDownload(arg1:main.StartDownloadRequest):Promise<main.DownloadTaskSnapshot>;
